Layout/LineLength:
    Max: 255

Layout/IndentationWidth:
    Width: 4

Layout/EmptyLinesAroundBlockBody:
    EnforcedStyle: no_empty_lines

Style/AccessorGrouping:
    Enabled: false

Naming/MethodParameterName:
    MinNameLength: 1

Style/For:
    Enabled: false

Metrics/BlockLength:
    Max: 100
